#!/bin/bash

echo "🔐 GitHub Git Credentials Setup"
echo "================================"
echo ""
echo "Follow these steps:"
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Give it a name like 'Railway Deploy'"
echo "4. Check the 'repo' scope checkbox"
echo "5. Click 'Generate token'"
echo "6. COPY THE TOKEN (you won't see it again!)"
echo ""
echo "Then run these commands:"
echo ""
echo "  git remote set-url origin https://github.com/DOTNETTMiller/traffic-dashboard-backend.git"
echo "  git push -u origin main"
echo ""
echo "When prompted for username: DOTNETTMiller"
echo "When prompted for password: PASTE YOUR TOKEN"
echo ""
echo "Your token will be saved in macOS Keychain for future use."
