-- Migration: Add IPAWS Rules Table
-- Description: Creates table for storing automated IPAWS alert rules with trigger conditions,
--              geofence configuration, and population filtering settings

CREATE TABLE IF NOT EXISTS ipaws_rules (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  enabled BOOLEAN DEFAULT true,

  -- Rule trigger conditions (stored as JSONB for flexibility)
  -- Example: {"corridors": ["I-80", "US-30"], "eventTypes": ["construction"],
  --           "severity": ["high"], "minLanesAffected": 1, "maxLanesAffected": 2}
  conditions JSONB NOT NULL DEFAULT '{}',

  -- Geofence configuration
  -- Example: {"type": "auto", "bufferMiles": 1.5, "customPolygon": null}
  geofence_config JSONB NOT NULL DEFAULT '{"type": "auto", "bufferMiles": 1}',

  -- Population filtering configuration
  -- Example: {"maxPopulation": 5000, "excludeUrbanAreas": true, "minPopulationDensity": 0}
  population_config JSONB NOT NULL DEFAULT '{"maxPopulation": 5000, "excludeUrbanAreas": true}',

  -- Whether alerts generated by this rule require supervisor approval
  requires_approval BOOLEAN DEFAULT false,

  -- Audit fields
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  created_by VARCHAR(255),

  -- Metadata
  last_triggered_at TIMESTAMP,
  trigger_count INTEGER DEFAULT 0
);

-- Index for faster rule lookups
CREATE INDEX IF NOT EXISTS idx_ipaws_rules_enabled ON ipaws_rules(enabled);
CREATE INDEX IF NOT EXISTS idx_ipaws_rules_conditions ON ipaws_rules USING GIN(conditions);

-- Table for tracking IPAWS alerts generated by rules
CREATE TABLE IF NOT EXISTS ipaws_alert_history (
  id SERIAL PRIMARY KEY,
  rule_id INTEGER REFERENCES ipaws_rules(id) ON DELETE SET NULL,
  event_id VARCHAR(255),
  alert_data JSONB NOT NULL,
  status VARCHAR(50) DEFAULT 'pending', -- pending, approved, sent, rejected
  generated_at TIMESTAMP DEFAULT NOW(),
  approved_at TIMESTAMP,
  approved_by VARCHAR(255),
  sent_at TIMESTAMP
);

-- Index for alert history queries
CREATE INDEX IF NOT EXISTS idx_ipaws_alert_history_rule_id ON ipaws_alert_history(rule_id);
CREATE INDEX IF NOT EXISTS idx_ipaws_alert_history_status ON ipaws_alert_history(status);
CREATE INDEX IF NOT EXISTS idx_ipaws_alert_history_generated_at ON ipaws_alert_history(generated_at DESC);

-- Insert example rules for common scenarios
INSERT INTO ipaws_rules (name, description, conditions, geofence_config, population_config, requires_approval)
VALUES
  (
    'I-80 Lane Reduction Alert',
    'Trigger IPAWS alert when I-80 is reduced to one lane in rural areas',
    '{"corridors": ["I-80"], "minLanesAffected": 1}',
    '{"type": "auto", "bufferMiles": 1.5}',
    '{"maxPopulation": 3000, "excludeUrbanAreas": true}',
    false
  ),
  (
    'High Severity Interstate Closures',
    'Automatic alerts for high severity closures on major interstates',
    '{"corridors": ["I-80", "I-35", "I-380", "I-680"], "severity": ["high"], "eventTypes": ["closure", "incident"]}',
    '{"type": "auto", "bufferMiles": 2}',
    '{"maxPopulation": 5000, "excludeUrbanAreas": true}',
    true
  ),
  (
    'US Highway Construction Alerts',
    'Alerts for construction events on US highways affecting multiple lanes',
    '{"corridors": ["US-30", "US-65", "US-20"], "eventTypes": ["construction"], "minLanesAffected": 2}',
    '{"type": "auto", "bufferMiles": 1}',
    '{"maxPopulation": 4000, "excludeUrbanAreas": true}',
    false
  )
ON CONFLICT DO NOTHING;

COMMENT ON TABLE ipaws_rules IS 'Automated IPAWS alert generation rules with configurable trigger conditions';
COMMENT ON COLUMN ipaws_rules.conditions IS 'JSONB field containing rule trigger conditions (corridors, event types, severity, lanes affected)';
COMMENT ON COLUMN ipaws_rules.geofence_config IS 'JSONB field for geofence generation settings (auto vs custom, buffer distance)';
COMMENT ON COLUMN ipaws_rules.population_config IS 'JSONB field for population filtering (max population, exclude urban areas)';
COMMENT ON TABLE ipaws_alert_history IS 'History of IPAWS alerts generated by automated rules';
